# Generated by Django 2.1.5 on 2020-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=300, null=True),
        ),
    ]
