# Generated by Django 2.1.5 on 2020-11-16 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userdata', '0002_content_expertise_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=300)),
                ('branchmanager_mobilenumber', models.IntegerField(default=0)),
                ('branch_mobilenumber', models.IntegerField(default=0)),
                ('storemanager_mobilenumber', models.IntegerField(default=0)),
                ('store_number', models.IntegerField(default=0)),
                ('activity', models.CharField(max_length=300, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('commercial_Regno', models.IntegerField(default=0)),
                ('storeManager_name', models.CharField(blank=True, max_length=300, null=True)),
                ('store_application', models.CharField(blank=True, max_length=300, null=True)),
                ('unified_number', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
