# Generated by Django 2.1.5 on 2020-11-16 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userdata', '0003_auto_20201116_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.IntegerField(default=0)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('nationality', models.CharField(blank=True, max_length=300, null=True)),
                ('indentitynumber', models.IntegerField(default=0)),
                ('driving_license', models.ImageField(upload_to='licenses')),
                ('car_form', models.ImageField(upload_to='carForms')),
                ('preffered_city', models.CharField(max_length=300, null=True)),
                ('mobile_number', models.IntegerField(max_length=300, null=True)),
                ('mobile_type', models.CharField(blank=True, max_length=300, null=True)),
                ('free_time', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
